# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

# Let's define a one-dimensional array 


[50, 60, 80, 100, 200, 300, 500, 600]

In [2]:
# Let's create a numpy array from the list "my_list"


array([ 50,  60,  80, 100, 200, 300, 500, 600])

numpy.ndarray

In [4]:
# Multi-dimensional (Matrix definition) 


array([[2, 5, 8],
       [7, 3, 6]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [6]:
# "rand()" uniform distribution between 0 and 1


array([0.24550682, 0.92290457, 0.4982003 , 0.44254441, 0.64748482,
       0.07986556, 0.70048155, 0.0986679 , 0.79340111, 0.31828063,
       0.54551631, 0.61038962, 0.15794414, 0.17205903, 0.66409968,
       0.4449435 , 0.03330255, 0.46514692, 0.40425268, 0.49549523])

In [7]:
# you can create a matrix of random number as well


array([[0.39727509, 0.98642314, 0.83894724],
       [0.96241275, 0.00115693, 0.05789424],
       [0.34128873, 0.09261359, 0.26125384]])

In [9]:
# "randint" is used to generate random integers between upper and lower bounds


15

In [10]:
# "randint" can be used to generate a certain number of random itegers as follows


array([15,  6, 69,  8, 71, 53, 52, 42, 18, 56, 98, 50, 83, 31, 10])

In [11]:
# np.arange creates an evenly spaced values within a given interval


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [12]:
# create a diagonal of ones and zeros everywhere else


array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [13]:
# Matrix of ones


array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [14]:
# Array of zeros


array([0., 0., 0., 0., 0., 0., 0., 0.])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [16]:
# np.arange() returns an evenly spaced values within a given interval


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Add 2 numpy arrays together


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [27]:
# Access specific index from the numpy array


3

In [28]:
# Starting from the first index 0 up until and NOT including the last element


array([3, 5, 6])

In [29]:
# Broadcasting, altering several values in a numpy array at once


array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [30]:
# Let's define a two dimensional numpy array


array([[6, 9, 7, 1],
       [6, 5, 5, 5],
       [6, 9, 1, 8],
       [8, 9, 3, 1]])

In [31]:
# Get a row from a mtrix


array([6, 9, 1, 8])

In [32]:
# Get one element


7

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

array([[4, 4, 3, 9, 6],
       [9, 9, 8, 9, 2],
       [4, 2, 1, 3, 3],
       [8, 1, 1, 6, 3],
       [1, 3, 6, 8, 8]])

array([9, 9, 9, 8, 9, 8, 8, 8])

In [44]:
# Obtain odd elements only


array([3, 9, 9, 9, 9, 1, 3, 3, 1, 1, 3, 1, 3])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [ ]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [53]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary


Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [54]:
# Let's obtain the data type 


pandas.core.frame.DataFrame

In [55]:
# you can only view the first couple of rows using .head()


Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4

In [56]:
# you can only view the last couple of rows using .tail()


Bank client ID Bank Client Name  Net worth [$]  Years with bank
3             444             Ryan           2000                5

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [62]:
# Pandas is used to read a csv file and store data in a DataFrame


First Name Last Name              Email Postal Code   Net Worth
0     Joseph    Patton     daafeja@boh.jm     M6U 5U7  $2,629.13 
1       Noah     Moran  guutodi@bigwoc.kw     K2D 4M9  $8,626.96 
2       Nina    Keller    azikez@gahew.mr     S1T 4E6  $9,072.02

In [64]:
# Read tabular data using read_html


City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

# TASK #8: PANDAS OPERATIONS

In [67]:
# Let's define a dataframe as follows:


Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [68]:
# Pick certain rows that satisfy a certain criteria 


Bank client ID Bank Client Name  Net worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [69]:
# Delete a column from a DataFrame


Bank Client Name  Net worth [$]  Years with bank
0           Chanel           3500                3
1            Steve          29000                4
2            Mitch          10000                9
3             Ryan           2000                5

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

# TASK #9: PANDAS WITH FUNCTIONS

In [71]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [73]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 


In [74]:
# You can apply a function to the DataFrame 


0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [80]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [81]:
# You can sort the values in the dataframe according to number of years with bank


Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [82]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True


Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [83]:
# Set inplace = True to ensure that change has taken place in memory 


In [84]:
# Note that now the change (ordering) took place 


Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [90]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

MINI CHALLENGE #1 SOLUTION: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [5]:
x = np.array([[[3, 7, 9, 3] , [4, 3, 2, 2]]])
x

array([[[3, 7, 9, 3],
        [4, 3, 2, 2]]])

MINI CHALLENGE #2 SOLUTION:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [15]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 10)
x

Please enter a positive integer value: 7


array([6, 5, 3, 5, 4, 2, 3, 3, 2, 1])

MINI CHALLENGE #3 SOLUTION:
- Given the X and Y values below, obtain the distance between them


```
X = [5, 7, 20]
Y = [9, 15, 4]
```




In [22]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
Z = np.sqrt(X**2 + Y**2)
Z

array([10.29563014, 16.55294536, 20.39607805])

MINI CHALLENGE #4 SOLUTION:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [33]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [34]:
X[4] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

MINI CHALLENGE #5 SOLUTION:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [41]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X<0] = 0
X[X%2==1] = -2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

MINI CHALLENGE #6 SOLUTION:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [58]:
portfolio_df = pd.DataFrame({'stock ticker symbols':['AAPL', 'AMZN', 'T'],
                             'price per share [$]':[3500, 200, 40], 
                             'Number of stocks':[3, 4, 9]})
portfolio_df

stock ticker symbols  price per share [$]  Number of stocks
0                 AAPL                 3500                 3
1                 AMZN                  200                 4
2                    T                   40                 9

In [59]:
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']
print(stocks_dollar_value)
print('Total portfolio value = {}'.format(stocks_dollar_value.sum()))

0    10500
1      800
2      360
dtype: int64
Total portfolio value = 11660


MINI CHALLENGE #7 SOLUTION:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [ ]:
# Read tabular data using read_html
retirement_age_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_age_df

MINI CHALLENGE #8 SOLUTION:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [ ]:
df_high_networth = bank_client_df[ (bank_client_df['Net worth [$]'] >= 5000) ]
df_high_networth

In [ ]:
df_high_networth['Net worth [$]'].sum()

MINI CHALLENGE #9 SOLUTION:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [77]:
def networth_update(balance):
    return balance * 3 + 200 

In [78]:
# You can apply a function to the DataFrame 
results = bank_client_df['Net worth [$]'].apply(networth_update)
results

0    10700
1    87200
2    30200
3     6200
Name: Net worth [$], dtype: int64

In [79]:
results.sum()

134300

PROJECT SOLUTION:

In [ ]:
# Creating a dataframe from a dictionary
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5 

raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1


# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2


# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary


# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all


# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all


In [104]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

Bank Client ID First Name Last Name  Annual Salary [$/year]
0             11         Ry       Aly                    1000

In [105]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df

Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Bob                   23000
9             10      Holly   Michelle                   22000
0             11         Ry        Aly                    1000